# Generated by Django 5.0.6 on 2024-05-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todolist",
            old_name="date_time",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="todolist",
            old_name="string",
            new_name="name",
        ),
    ]
